### ISSUE TITLE
how can i get the zeroshot_triplet.pytorch1807?

### ISSUE THREAD

**Issue by ZHUXUHAN** [waxnkw/IETrans-SGG.pytorch#11]
FileNotFoundError: [Errno 2] No such file or directory: 'maskrcnn_benchmark/data/datasets/evaluation/vg/zeroshot_triplet.pytorch1807'

**Comment by waxnkw** [comment]
Sorry for forgetting to upload this. Due to the reason that I do not care about zero-shot performance on VG-1800. I just copy zeroshot_triplet.pytorch50 as zeroshot_triplet.pytorch1807. You can just go to `maskrcnn_benchmark/data/datasets/evaluation/vg/` and run `cp zeroshot_triplet.pytorch50 zeroshot_triplet.pytorch1807`

**Comment by ZHUXUHAN** [comment]
> Sorry for forgetting to upload this. Due to the reason that I do not care about zero-shot performance on VG-1800. I just copy zeroshot_triplet.pytorch50 as zeroshot_triplet.pytorch1807. You can just go to `maskrcnn_benchmark/data/datasets/evaluation/vg/` and run `cp zeroshot_triplet.pytorch50 zeroshot_triplet.pytorch1807`

ok,this right, thanks.
